"""add terms_accepted field

Revision ID: 0eb6e26b4a73
Revises: 9a9a28062a51
Create Date: 2024-12-04 05:18:00.532137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb6e26b4a73'
down_revision = '9a9a28062a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('custom_css')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted')

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_css', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
