"""add birth_date and age_verified fields

Revision ID: 8f1ac01e9fcc
Revises: 0eb6e26b4a73
Create Date: 2024-12-04 05:22:24.211494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1ac01e9fcc'
down_revision = '0eb6e26b4a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('age_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age_verified')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
